### ISSUE TITLE
Support non-interactive mode

### ISSUE THREAD

**Issue by agateblue** [GreatWizard/reliure#51]
Hi! I'm trying to use Reliure to build epubs for some of my posts on a jekyll static site, as part of the site build process. Everything happens non interactively. I'm running reliure with `reliure --epub .` and the following config file:

```yaml
filename: Test

default:
  files:
    - data/test.md


  metadata:
    title: Test Book
    author: Test
    date: 2020-11
    lang: fr-FR                                                             
```

Unfortunately, even if I'm not trying to build a mobi version, I still get the prompt to accept the KindleGen terms of use, which I can't easily do since the whole things run on a Gitlab CI runner:

```
KindleGen is a tool to convert files to the Kindle format (Mobi) enabling publishers to create great-looking books that work on all Kindle devices and apps.
KindleGen is officially supported by Amazon.
To install KindleGen, you must accept the following terms of use: https://www.amazon.com/gp/feature.html?docId=1000599251
? Do you agree to terms of use? (Y/n) 
```

Do you think it could be possible to disable this entirely when Mobi is not built, or through a CLI flag to run Reliure in non-interactive mode?
