### ISSUE TITLE
`opfSubstitutions` work only partially

### ISSUE THREAD

**Issue by BlueCutOfficial** [GreatWizard/reliure#62]
I tried to work around issue #61 by using `opfSubstitutions` to add some `properties="svg"` attributes in the `<manifest>` of my content.opf file. 

```yml
opfSubstitutions:
    - regex: <item id="ch002_xhtml" href="text/ch002.xhtml" media-type="application/xhtml+xml" />
      replacement: <item id="ch002_xhtml" href="text/ch002.xhtml" media-type="application/xhtml+xml" properties="svg" />
```

It doesn't work. 

I tested the example in the README:

```
opfSubstitutions:
    - regex: <dc:language>fr-FR</dc:language>
      replacement: <dc:language>fr-BE</dc:language>
```

This one does work, so it seems the replacement works for part of the content but not for my manifest items.
